#!/usr/bin/env bun
/**
 * Generates build-time dot data for all blog post icons so PixelIconDisplay
 * can render instantly (no runtime canvas/blob/image rasterization).
 *
 * Replicates the exact runtime pipeline of DotMatrixIcon.tsx:
 *   renderToStaticMarkup(<PhosphorIcon size={48} weight="regular" />)  (same as the hidden-container path)
 *   -> rasterize at gridSize 32 -> sample pixels with alpha > 50
 * Custom icons (frontmatter "xxx.svg") are rasterized straight from public/blog-headers/.
 *
 * Icon keys are the lowercased frontmatter `icon` values. Alignment is NOT baked -
 * it is applied at render time from component props.
 *
 * Run: bun run icons:generate
 */

import { createCanvas, loadImage } from "@napi-rs/canvas";
import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync } from "fs";
import { join } from "path";
import React from "react";
import { renderToStaticMarkup } from "react-dom/server";
import * as PhosphorIcons from "@phosphor-icons/react";

const CONTENT_DIR = join(process.cwd(), "content", "blog");
const BLOG_HEADERS_DIR = join(process.cwd(), "public", "blog-headers");
const OUTPUT_FILE = join(process.cwd(), "app", "generated", "icon-dots.ts");

// Must match the params used by the runtime pipeline for post icons
const GRID_SIZE = 32;
const ICON_RENDER_SIZE = 48;

// Fallback icon used by normalizeFrontmatter when frontmatter omits it
const FALLBACK_ICON = "newspaper";

function collectIconKeys(): { raw: string; key: string }[] {
	// key = lowercased bake key, raw = original frontmatter casing (needed to resolve the component)
	const map = new Map<string, string>();

	for (const file of readdirSync(CONTENT_DIR)) {
		if (!file.endsWith(".mdx")) continue;
		const content = readFileSync(join(CONTENT_DIR, file), "utf-8");
		const match = content.match(/^icon:\s*"([^"]+)"/m);
		if (match?.[1]) {
			const raw = match[1].trim();
			map.set(raw.toLowerCase(), raw);
		}
	}

	if (!map.has(FALLBACK_ICON)) map.set(FALLBACK_ICON, FALLBACK_ICON);
	return [...map.entries()].map(([key, raw]) => ({ raw, key }));
}

function resolvePhosphorComponent(name: string) {
	// Same normalization as resolvePhosphorIcon in app/utils/icons.ts
	const normalized = name.replace(/Icon$/i, "");
	const pascalCase = normalized.charAt(0).toUpperCase() + normalized.slice(1);
	const icons = PhosphorIcons as unknown as Record<string, any>;
	return icons[`${pascalCase}Icon`] ?? PhosphorIcons.NewspaperIcon;
}

async function rasterize(svgString: string): Promise<[number, number][]> {
	const svgBase64 = Buffer.from(svgString).toString("base64");
	const image = await loadImage(`data:image/svg+xml;base64,${svgBase64}`);
	const canvas = createCanvas(GRID_SIZE, GRID_SIZE);
	const ctx = canvas.getContext("2d");
	ctx.clearRect(0, 0, GRID_SIZE, GRID_SIZE);
	ctx.drawImage(image, 0, 0, GRID_SIZE, GRID_SIZE);

	const data = ctx.getImageData(0, 0, GRID_SIZE, GRID_SIZE).data;
	const pixels: [number, number][] = [];

	for (let y = 0; y < GRID_SIZE; y++) {
		for (let x = 0; x < GRID_SIZE; x++) {
			const index = (y * GRID_SIZE + x) * 4;
			if (data[index + 3] > 50) pixels.push([x, y]);
		}
	}

	return pixels;
}

async function main(): Promise<void> {
	const keys = collectIconKeys();
	const entries: string[] = [];

	for (const { raw, key } of keys) {
		try {
			let svgString: string;

			if (key.endsWith(".svg")) {
				const filePath = join(BLOG_HEADERS_DIR, key);
				if (!existsSync(filePath)) {
					console.error(`Skipping "${key}" - file not found at ${filePath}`);
					continue;
				}
				svgString = readFileSync(filePath, "utf-8");
			} else {
				// Same render as the runtime hidden-container path (size 48, regular weight)
				const normalized = raw.replace(/Icon$/i, "");
				const pascalCase = normalized.charAt(0).toUpperCase() + normalized.slice(1);
				const Icon = (PhosphorIcons as unknown as Record<string, any>)[`${pascalCase}Icon`] ?? PhosphorIcons.NewspaperIcon;
				svgString = renderToStaticMarkup(React.createElement(Icon, { size: ICON_RENDER_SIZE, weight: "regular" }));
			}

			const pixels = await rasterize(svgString);
			entries.push(`\t"${key}": { gridSize: ${GRID_SIZE}, pixels: ${JSON.stringify(pixels)} }`);
			console.log(`✓ ${key} (from "${raw}") (${pixels.length} pixels)`);
		} catch (error) {
			console.error(`✗ ${key}:`, error instanceof Error ? error.message : error);
		}
	}

	const output = `// AUTO-GENERATED by scripts/generate-icon-dots.ts - do not edit manually.
// Regenerate with: bun run icons:generate
// Raw pixel samples per icon at gridSize ${GRID_SIZE}. Alignment is applied at render time.

export type IconDotData = { gridSize: number; pixels: [number, number][] };

export const ICON_DOTS: Record<string, IconDotData> = {
${entries.join(",\n")}
};
`;

	mkdirSync(join(process.cwd(), "app", "generated"), { recursive: true });
	writeFileSync(OUTPUT_FILE, output);
	console.log(`\nWritten to ${OUTPUT_FILE}`);
}

main();
